### PR TITLE
Fix extension error when form contains elements with name set to "id" or "name"

### LINKED ISSUE #297: Kee for Chrome is not working with Drupal sites
Hi, the latest version causes problems on some sites based on Drupal. Please see the example: https://handytools.pro/user/login

When I visit if from two different machines that use common .kbdx file (Chrome@Ubuntu and Chrome@Windows), the credentials for this url are not detected. Instead, I get 34 errors in the console:

```
Error in event handler: TypeError: _b.toLowerCase is not a function
    at ConfigManager.isFormInteresting (<URL>)
    at FormFilling.findMatchesInThisFrame (<URL>)
    at <URL>
login:1 Error in event handler: TypeError: _b.toLowerCase is not a function
    at ConfigManager.isFormInteresting (chrome-extension://mmhlniccooihdimnnjhamobppdhaolme/common/common.js:16:25441)
    at FormFilling.findMatchesInThisFrame (chrome-extension://mmhlniccooihdimnnjhamobppdhaolme/page/page.js:1:18829)
    at chrome-extension://mmhlniccooihdimnnjhamobppdhaolme/page/page.js:1:55177
```
This happens for Drupal 7, Drupal 8 and Drupal 9, so it means millions of sites.

### PR DESCRIPTION
**Pull request by burtek**
Fixes extension error when form contains elements with `name` attribute set to "id" or "name". See https://github.com/kee-org/browser-addon/issues/297#issuecomment-772832415, https://forum.kee.pm/t/kee-browser-extension-bug-using-form-name-rather-than-form-getattribute-name/3503/3 and https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/name

Bug introduced in https://github.com/kee-org/browser-addon/commit/21efb9d5baccc90f9cce11cdfca24161a08867e2#diff-28be9268beaee14e36d782ac5832cab19593348724c0caf74b2d79c0d349257eR454-R455

Fixes #297

### CODE REVIEW

**Comment by luckyrat** [comment]
Thanks for the PR.

Unfortunately if we use `getAttribute` we can miss legitimate values for name and id that are set by Javascript code.

Therefore, I think we should use that as a fallback only if `form.id` or `form.name` are not strings.

Realistically, I'm not even sure if any websites will actually set the form `name` attribute if they use a field with `name=name` but we need to be sure we don't introduce any regression while fixing this issue.

Would you be able to update your PR as suggested above?

Don't worry too much about the commit descriptions - I'll squash and rebase onto master when you're done anyway.

**Comment by burtek** [comment]
Sure, will change that in about an hour

czw., 4 lut 2021, 17:25 użytkownik Chris Tomlinson <notifications@github.com>
napisał:

**Comment by burtek** [comment]
@luckyrat done. Sorry about those commits, had not yet configured my IDE fully on new PC and was kinda editing it in scratchpad
